services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    depends_on:
      - auth
    networks:
      - backend

  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      retries: 10
      timeout: 2s

  auth:
    build:
      context: ./backend
      dockerfile: apps/auth/Dockerfile
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50054:50054" 
    networks:
      - backend


  redis:
    image: redis:7.0
    container_name: redis
    command: ["redis-server", "--requirepass", "${CACHE_PASSWORD}"]
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
