services:
  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      retries: 10
      timeout: 2s

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    env_file: 
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:9090"
    networks:
      - backend

networks:
  backend:
    driver: bridge
