# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0c\n\x04user\x18\x02 \x01(\t2\xb4\x01\n\x0b\x41uthService\x12\x39\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x16.google.protobuf.Empty\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12\x39\n\x08Validate\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponseB\x1bZ\x19\x62\x61\x63kend/pkg/gen/auth;authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031backend/pkg/gen/auth;auth'
  _globals['_REGISTERREQUEST']._serialized_start=49
  _globals['_REGISTERREQUEST']._serialized_end=102
  _globals['_LOGINREQUEST']._serialized_start=104
  _globals['_LOGINREQUEST']._serialized_end=154
  _globals['_AUTHRESPONSE']._serialized_start=156
  _globals['_AUTHRESPONSE']._serialized_end=205
  _globals['_VALIDATEREQUEST']._serialized_start=207
  _globals['_VALIDATEREQUEST']._serialized_end=239
  _globals['_VALIDATERESPONSE']._serialized_start=241
  _globals['_VALIDATERESPONSE']._serialized_end=288
  _globals['_AUTHSERVICE']._serialized_start=291
  _globals['_AUTHSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
